name: terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./

jobs:
  plan-workflows:
    runs-on: ubuntu-22.04
    environment: actions
    env:
      TZ: 'Asia/Tokyo'
      TF_VAR_repository: ${{ vars.TF_VAR_repository }}
      TF_VAR_project: ${{ vars.TF_VAR_project }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_zone: ${{ vars.TF_VAR_zone }}
      TF_VAR_tf_service_account: ${{ vars.TF_VAR_tf_service_account }}
      DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.TF_VAR_tf_service_account }}
          access_token_lifetime: 1200s
          create_credentials_file: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - uses: hashicorp/setup-terraform@v2

      - name: 'Terraform init'
        run: make tf-init

      - name: 'Terraform plan'
        run: make tf-plan
